config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  namespace :public do
    get 'homes/about'
    resources :items, only: [:index, :show]
    resources :orders, only: [:new, :index, :show, :create, :confirm] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end
    resources :genres, only: [:show]
    resources :customers, only: [:show, :edit, :update, :unsubscribe, :withdrawal]
    get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch '/customers/:id/withdrawal' => 'customers#withdrawl', as: 'withdrawal'
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy]
  end


  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    get 'homes/top'
    resources :genres, only: [:index, :edit, :create, :update]
    resources :orders, only: [:show]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:index, :show, :edit, :new, :create, :update]
    patch '/admin/genres/:id' => 'genres#update', as: 'update'
    patch '/admin/items/:id' => 'items#update', as: 'update_item'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def active_for_authentication?
    super && (is_deleted == false)
  end


  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customer = Customer.all
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    customer = Customer.find(params[:id])
    if customer.update(customer_params)
      redirect_to admin_customer_path(customer.id)
    else
      render :edit
    end
  end

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana,
    :postal_code, :address, :telephone_number, :email, :is_deleted)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<%= form_with model: @customer, url: admin_customer_path do |f| %>


<div class="container px-5 px-sm-0 mt-3">
  <div class="row">
    <div class="offset-md-1 pb-5 mb-5">
      <h5 class="d-inline-block my-4 bg-light">　<%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集　</h5>
      <table class="table table-sm table-borderless">
        <tr>
          <td><%= f.label "会員ID" %></td>
          <td><%= @customer.id %></td>
          <td><br></td>
        </tr>
        <tr>
          <td class="pr-5"><%= f.label "氏名" %></td>
          <td class="pr-5"><%= f.text_field :last_name %></td>
          <td><%= f.text_field :first_name %></td>
        </tr>
        <tr>
          <td class="pr-5"><%= f.label "フリガナ" %></td>
          <td class="pr-5"><%= f.text_field :last_name_kana %></td>
          <td><%= f.text_field :first_name_kana %></td>
        </tr>
        <tr>
          <td class="pr-3"><%= f.label "郵便番号" %></td>
          <td class="pr-5"><%= f.text_field :postal_code %></td>
          <td><br></td>
        </tr>
        <tr>
          <td class="pr-5"><%= f.label "住所" %></td>
          <td colspan="3"><%= f.text_field :address, class: "col-12" %></td>
          <td><br></td>
        </tr>
        <tr>
          <td class="pr-5"><%= f.label "電話番号" %></td>
          <td><%= f.text_field :telephone_number %></td>
          <td><br></td>
        </tr>
        <tr>
          <td class="pr-5"><%= f.label "メールアドレス" %></td>
          <td class="pr-5"><%= f.email_field :email, autocomplete: "email" %></td>
          <td><br></td>
        </tr>
        <tr>
          <td class="pr-5"><%= f.label "会員ステータス" %></td>
          <td class="pr-5">
            <label><%= f.radio_button :is_deleted, false %>有効</label>
            <label><%= f.radio_button :is_deleted, true %>無効</label>
          </td>
          <td><br></td>
        </tr>
        <tr>
          <td class="pr-5"></br></td>
          <td><%= f.submit "変更を保存", class: "btn btn-success rounded btn-sm d-grid gap-2 col-8 mx-auto" %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

<% end %>

app/views/admin/customers/index.html.erb
<%= form_with model: @customer, url: admin_items_path do |f| %>
<div class="container-fluid">
  <div class="row">
    <div class="offset-md-1">
      <h5 class="d-inline-block m-4 ml-5 bg-light">　会員一覧　</h5>
    </div>
  </div>
  <div class="row　justify-content-center">
    <div class="mx-auto col-md-8 col-md-offset-2 ">
        <table class="table">
          <thead class="bg-light">
            <tr>
              <th>会員ID</th>
              <th>氏名</th>
              <th>メールアドレス</th>
              <th>ステータス</th>
            </tr>
          </thead>
            <tbody>
              <% @customer.each do |customer| %>
                <tr>
                  <td>
                    <%= customer.id %>
                  </td>
                  <td>
                    <%= link_to admin_customer_path(customer.id) do %>
                      <%= customer.last_name %><%= customer.first_name %>
                    <% end %>
                  </td>
                  <td>
                    <%= customer.email %>
                  </td>
                  <td>
                    <%= customer.is_deleted? ? '無効' : '有効' %>
                  </td>
                </tr>
              <% end %>
            </tbody>
        </table>
      </div>
      </div>
  </div>
</div>

<% end %>
<%= paginate @customers %>

app/views/admin/customers/show.html.erb
<%= form_with model: @customer, url: admin_customer_path do |f| %>


<div class="container px-5 px-sm-0 mt-3">
  <div class="row">
    <div class="offset-md-1 pb-5 mb-5">
      <h5 class="d-inline-block my-4 bg-light">　<%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細　</h5>
      <table class="table table-sm table-borderless">
        <tr>
          <td><%= f.label "会員ID" %></td>
          <td><%= @customer.id %></td>
          <td><br></td>
        </tr>
        <tr>
          <td><%= f.label "氏名" %></td>
          <td><%= @customer.last_name %><%= @customer.first_name %></td>
          <td><br></td>
        </tr>
        <tr>
          <td><%= f.label "フリガナ" %></td>
          <td><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
          <td><br></td>
        </tr>
        <tr>
          <td><%= f.label "郵便番号" %></td>
          <td><%= @customer.postal_code %></td>
          <td><br></td>
        </tr>
        <tr>
          <td><%= f.label "住所" %></td>
          <td><%= @customer.address %></td>
          <td><br></td>
        </tr>
        <tr>
          <td><%= f.label "電話番号" %></td>
          <td><%= @customer.telephone_number %></td>
          <td><br></td>
        </tr>
        <tr>
          <td class="pr-5"><%= f.label "メールアドレス" %></td>
          <td><%= @customer.email %></td>
          <td><br></td>
        </tr>
        <tr>
          <td><%= f.label "会員ステータス" %></td>
          <td><%= @customer.is_deleted? ? '無効' : '有効' %></td>
          <td><br></td>
        </tr>
        <tr>
          <td><br></td>
          <td><%= link_to "編集する", edit_admin_customer_path, class: "btn btn-success rounded btn-sm d-grid gap-2 col-8 mx-auto" %></td>
          <td><%= link_to "注文履歴一覧を見る", admin_homes_top_path, class: "btn btn-primary rounded btn-sm d-grid gap-2  mx-auto" %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

<% end %>