config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  namespace :public do
    get 'homes/about'
    resources :items, only: [:index, :show]
    resources :orders, only: [:new, :index, :show, :create, :confirm] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end
    resources :genres, only: [:show]
    resources :customers, only: [:show, :edit, :update, :unsubscribe, :withdrawal]
    get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch '/customers/:id/withdrawal' => 'customers#withdrawl', as: 'withdrawal'
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy]
  end


  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    get 'homes/top'
    resources :genres, only: [:index, :edit, :create, :update]
    resources :orders, only: [:show]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:index, :show, :edit, :new, :create, :update]
    patch '/admin/genres/:id' => 'genres#update', as: 'update'
    patch '/admin/items/:id' => 'items#update', as: 'update_item'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :image

  

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  validates :amount, presence: true

  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def active_for_authentication?
    super && (is_deleted == false)
  end


  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      image.variant(resize_to_limit: [width, height]).processed
  end

  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
  has_many :items, through: :order_items
  belongs_to :customer

  enum payment_method: { credit_card: 0, transfer: 1 }

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :item
  belongs_to :order


  def subtotal
    @order_item.tax_included_price * amount
  end

  def s_total
    @order_item.tax_included_price * @order_item.amount
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    if @genre = Genre.find(params[:id])
      @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name, :genre_id)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @order = Order.all
  end



end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all

  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    if item = Item.find(params[:id])
      item.update(item_params)
      redirect_to admin_item_path(item.id)
    else
      render :edit
    end
  end


  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :genre_id )
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_item = @order.order_items
  end

  def order_params
      params.require(:order).permit(:payment_method, :address, :postal_code, :receiver, :payment_amount, :postage, )
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana,
    :postal_code, :address, :telephone_number])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/1309c48d16.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="social"></div>
    <header>
      <nav class="navbar navbar-expand-md navbar-light bg-info">
        <div class="container">
          <a class="navbar-brand mt-4 mb-3" href="/"><h2><%= "LOGO" %></h2></a>
            <ul class="navbar-nav ml-auto"></ul>
            <% if customer_signed_in? %>
              <li class="nav-link btn btn-sm btn-outline-secondary rounded ml-5">
                <%= link_to "マイページ", public_customer_path(current_customer.id) %>
              </li>
              <li class="nav-link btn btn-sm btn-outline-secondary rounded ml-5">
                <%= link_to "商品一覧", public_items_path %>
              </li>
              <li class="nav-link btn btn-sm btn-outline-secondary rounded ml-5">
                <%= link_to "カート",  public_cart_items_path(current_customer.id) %>
              </li>
              <li class="nav-link btn btn-sm btn-outline-secondary rounded ml-5">
                <%= link_to "ログアウト", destroy_customer_session_path, method: :delete %>
              </li>
            <% elsif admin_signed_in? %>
              <li class="nav-link btn btn-sm btn-outline-secondary rounded ml-5">
                <%= link_to "商品一覧", admin_items_path %>
              </li>
              <li class="nav-link btn btn-sm btn-outline-secondary rounded ml-5">
                <%= link_to "会員一覧", admin_customers_path %>
              </li>
              <li class="nav-link btn btn-sm btn-outline-secondary rounded ml-5">
                <%= link_to "注文履歴一覧", admin_homes_top_path %>
              </li>
              <li class="nav-link btn btn-sm btn-outline-secondary rounded ml-5">
                <%= link_to "ジャンル一覧", admin_genres_path %>
              </li>
              <li class="nav-link btn btn-sm btn-outline-secondary rounded ml-5">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
              </li>
            <% else %>
              <li class="nav-link btn btn-sm btn-outline-secondary rounded ml-5">
                <%= link_to "About", public_homes_about_path %>
              </li>
              <li class="nav-link btn btn-sm btn-outline-secondary rounded ml-5">
                <%= link_to "商品一覧", public_items_path %>
              </li>
              <li class="nav-link btn btn-sm btn-outline-secondary rounded ml-5">
                <%= link_to "新規登録", new_customer_registration_path %>
              </li>
              <li class="nav-link btn btn-sm btn-outline-secondary rounded ml-5">
                <%= link_to "ログイン", new_customer_session_path %>
              </li>
              <% end %>
            </ul>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer class="bg-dark text-white pt-5 pb-4 fixed-bottom">
      <div class="container">
      </div>
    </footer>
  </body>
</html>